/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DatasourceAuthModal: typeof import('./src/components/datasource/datasource-auth-modal.vue')['default']
    DatasourceForm: typeof import('./src/components/datasource/datasource-form.vue')['default']
    IconifyIcon: typeof import('./src/components/IconifyIcon/index.vue')['default']
    LayoutDefault: typeof import('./src/components/Layout/default.vue')['default']
    LayoutSidebarPage: typeof import('./src/components/Layout/sidebar-page.vue')['default']
    LayoutSlotArea: typeof import('./src/components/Layout/SlotArea.vue')['default']
    LayoutSlotCenterPanel: typeof import('./src/components/Layout/SlotCenterPanel.vue')['default']
    LayoutSlotFrame: typeof import('./src/components/Layout/SlotFrame.vue')['default']
    LlmForm: typeof import('./src/components/llm/llm-form.vue')['default']
    MarkdownPreview: typeof import('./src/components/MarkdownPreview/index.vue')['default']
    MarkdownPreviewHtmlReportViewer: typeof import('./src/components/MarkdownPreview/HtmlReportViewer.vue')['default']
    MarkdownPreviewMarkdownAntv: typeof import('./src/components/MarkdownPreview/markdown-antv.vue')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NavigationNavBar: typeof import('./src/components/Navigation/nav-bar.vue')['default']
    NavigationNavFooter: typeof import('./src/components/Navigation/nav-footer.vue')['default']
    NavigationNavOctocat: typeof import('./src/components/Navigation/nav-octocat.vue')['default']
    NavigationNavSidebar: typeof import('./src/components/Navigation/nav-sidebar.vue')['default']
    NavigationSideBar: typeof import('./src/components/Navigation/SideBar.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NCheckboxGroup: typeof import('naive-ui')['NCheckboxGroup']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NDynamicInput: typeof import('naive-ui')['NDynamicInput']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NFormItemGi: typeof import('naive-ui')['NFormItemGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NPagination: typeof import('naive-ui')['NPagination']
    NPopover: typeof import('naive-ui')['NPopover']
    NRadioButton: typeof import('naive-ui')['NRadioButton']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NTag: typeof import('naive-ui')['NTag']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
